kind: Deployment
apiVersion: apps/v1
metadata:
  name: loghme7-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loghme7-front
  template:
    metadata:
      labels:
        app: loghme7-front
    spec:
      containers:
        - name: loghme7-front
          image: index.docker.io/tahashm/loghme:front
          imagePullPolicy: Always
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: loghme7-front
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32000
  selector:
    app: loghme7-front